Player.create!(name: "Dimitris")
Player.create!(name: "Alexandros")
Player.create!(name: "Mixalhs")
Player.create!(name: "Eleni")
Player.create!(name: "Kostis")
Player.create!(name: "Giannis")
Player.create!(name: "Bogdan")